# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'ConsolidationCountries' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConsolidationCountries
  pod 'Moya', '~> 14.0'

end
